; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

; Generated by VC++ for Common Language Runtime
.file "D:\Format_tool\Fatformat\Debug\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
